remote_theme: poole/hyde@v2.1.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
title: Nick Seewald's Slide Repository
description: A catch-all repository for Nick's posters and slides
show_downloads: false
github:
  - is_project_page: false
  - is_user_page: false
